PostHog/posthog-dotnet

- .github/workflows/main.yaml
- .github/workflows/release.yaml
- PostHog.sln
Also, handle the release `create` event.
> Separate package publishing into its own workflow

- .github/workflows/main.yaml
- .github/workflows/release.yaml
When we tag a release using the pattern `v*`, we'll upload the build artifacts. The release job will grab those artifacts and publish.
> Only publish on tag and release

- src/PostHog/Api/CapturedEvent.cs
- src/PostHog/Api/IPostHogApiClient.cs
- src/PostHog/Api/PostHogApiClient.cs
- src/PostHog/Generated/VersionConstants.cs
- src/PostHog/IPostHogClient.cs
- src/PostHog/PostHogClient.cs
- tests/UnitTests/Api/PostHogApiClientTests.cs
- tests/UnitTests/Fakes/FakeHttpMessageHandler.cs
I think capturing events was broken prior to this PR. But now it's fixed.
Fixes #27
> Fix sending the $lib property when capturing batches

- Directory.Build.props
- src/PostHog/Api/CapturedEvent.cs
- src/PostHog/Api/PostHogApiClient.cs
- src/PostHog/Generated/VersionConstants.cs
- tests/UnitTests/Api/PostHogApiClientTests.cs
When sending an event to PostHog, the server will "enrich" that event with GeoIP location data. However, for client libraries like this that are meant to be used on the server, that doesn't make much sense since it'll always be the location data of the server hosting this client.
This sets the `$geoip_disable` property to `true` which makes reading information about captured events from this library much easier.
If someone wants GeoIP enrichment, they can open an issue and I'll consider it.
356d70b
> Disable geoip enrichment

- Directory.Build.props
- src/PostHog.AspNetCore/PostHog.AspNetCore.csproj
.NET 8.0 is the latest LTS (Long Term Support) release. We should target that instead of .NET 9.
> Retarget to net8.0

- Directory.Build.props
- README.md
- samples/HogTied.Web/Pages/Index.cshtml.cs
- samples/HogTied.Web/Program.cs
- src/PostHog.AspNetCore/README.md
- src/PostHog/Api/PostHogApiClientExtensions.cs
- src/PostHog/Capture/CaptureExtensions.cs
- src/PostHog/Extensions/GroupIdentifyAsyncExtensions.cs
- src/PostHog/Extensions/IdentifyPersonAsyncExtensions.cs
- src/PostHog/Generated/VersionConstants.cs
- src/PostHog/IPostHogClient.cs
- src/PostHog/PostHogClient.cs
- tests/UnitTests/PostHogClientTests.cs
While I liked that the names were more explicit, being consistent with the other client libs will cause less overall confusion. Especially given how the docs refer to these methods.
> Rename methods to match other libraries

- README.md
Removed an unnecessary closing brace in the posthogClient.Capture call, ensuring correct syntax.
> fix: remove extra closing brace in capture call

- Directory.Build.props
- greptile.json
- src/PostHog/Api/ErrorApiResult.cs
- src/PostHog/Api/LocalEvaluationApiResult.cs
- src/PostHog/Api/PostHogApiClient.cs
- src/PostHog/Features/FeatureFlag.cs
- src/PostHog/Features/FeatureFlagExtensions.cs
- src/PostHog/Features/LocalEvaluator.cs
- src/PostHog/Features/LocalFeatureFlagsLoader.cs
- src/PostHog/Features/RemoteConfigExtensions.cs
- src/PostHog/Generated/VersionConstants.cs
- src/PostHog/IPostHogClient.cs
- src/PostHog/Json/FilterJsonConverter.cs
- src/PostHog/Library/HttpClientExtensions.cs
- src/PostHog/PostHogClient.cs
- tests/TestLibrary/Fakes/ConsoleTestOutputHelper.cs
- tests/TestLibrary/Fakes/FakeHttpMessageHandlerExtensions.cs
- tests/TestLibrary/Fakes/FakeLogger.cs
- tests/TestLibrary/Fakes/FakeLoggerProvider.cs
- tests/TestLibrary/TestContainer.cs
- tests/UnitTests/Features/FeatureFlagTests.cs
- tests/UnitTests/Features/FeatureFlagsTests.cs
- tests/UnitTests/Features/LocalEvaluatorTests.cs
- tests/UnitTests/Features/RemoteConfigTests.cs
- tests/UnitTests/Json/FilterSerializationTests.cs
- tests/UnitTests/Json/JsonSerializerHelperTests.cs
- tests/UnitTests/Library/JsonAssert.cs
- tests/UnitTests/PostHogClientTests.cs
- tests/UnitTests/UnitTests.csproj
This PR also improves exception handling so that exceptions thrown from methods retrieving flags are unlikely. Error situations are logged instead.
This also changes `FeatureFlag.Payload` to be a `JsonDocument`.
> Add support for remote config settings

- Directory.Build.props
- samples/HogTied.Web/Filters/PostHogPageViewFilter.cs
- samples/HogTied.Web/Pages/Index.cshtml.cs
- src/PostHog.AspNetCore/Registration.cs
- src/PostHog/Api/PostHogApiClient.cs
- src/PostHog/Config/PostHogOptions.cs
- src/PostHog/Examples.cs
- src/PostHog/Features/FeatureFlagOptions.cs
- src/PostHog/Features/LocalFeatureFlagsLoader.cs
- src/PostHog/Generated/VersionConstants.cs
- src/PostHog/Library/AsyncBatchHandler.cs
- src/PostHog/PostHogClient.cs
- tests/TestLibrary/TestContainer.cs
- tests/UnitTests/Features/FeatureFlagsTests.cs
- tests/UnitTests/Library/AsyncBatchHandlerTests.cs
- tests/UnitTests/PostHogClientTests.cs
No need to import another namespace for a common scenario.
> Move `PostHogOptions` and `FeatureFlagOptions` into PostHog namespace

- Directory.Build.props
- samples/HogTied.Web/Pages/Index.cshtml
- samples/HogTied.Web/Pages/Index.cshtml.cs
- src/PostHog/Generated/VersionConstants.cs
- src/PostHog/PostHogClient.cs
- tests/UnitTests/Features/RemoteConfigTests.cs
The remote config endpoint returns JSON encoded in a string.
`"{\"foo\": \"bar\",\"baz\": 42}"`
Instead of:
`{"foo": "bar","baz": 42}`
However, we may change that in the future.
So this is implemented in a forward-compatible way to handle both options.
> Fix accessing remote config settings

- src/PostHog/Api/ApiErrorResult.cs
- src/PostHog/Api/DecideApiResult.cs
- src/PostHog/Api/PostHogApiClient.cs
- src/PostHog/Features/LocalFeatureFlagsLoader.cs
- src/PostHog/Library/ApiException.cs
- src/PostHog/Library/HttpClientExtensions.cs
- src/PostHog/PostHogClient.cs
- tests/UnitTests/Features/FeatureFlagsTests.cs
with https://github.com/PostHog/posthog/pull/28564, we now start to respond different with the /decide and /local_evaluation APIs if users have gone over their quota limit. Now we need to change the SDKs to handle these new responses.
> feat(feature-flags): support quota limiting for feature flags #403

- Directory.Build.props
- samples/HogTied.Web/Filters/PostHogPageViewFilter.cs
- src/PostHog.AspNetCore/Config/IPostHogAspNetCoreConfigurationBuilder.cs
- src/PostHog.AspNetCore/FeatureManagement/IPostHogFeatureManagementBuilder.cs
- src/PostHog/Api/ApiResult.cs
- src/PostHog/Api/ComparisonOperator.cs
- src/PostHog/Api/PostHogApiClient.cs
- src/PostHog/Extensions/GroupIdentifyAsyncExtensions.cs
- src/PostHog/Extensions/IdentifyPersonAsyncExtensions.cs
- src/PostHog/Features/LocalEvaluator.cs
- src/PostHog/Generated/VersionConstants.cs
- src/PostHog/Json/InconclusiveMatchException.cs
- src/PostHog/Json/PropertyFilterValueJsonConverter.cs
- src/PostHog/Library/AsyncBatchHandler.cs
- src/PostHog/PostHogClient.cs
- tests/UnitTests/Features/LocalEvaluatorTests.cs
This bumps the version to 1.0.0 (removing the beta label).
It also adds some code documentation and changes the ctor for `PostHogClient` to accept nulls for each of the dependencies and provides a simple alternative when null.
> Prepare the 1.0.0 release

- Directory.Build.props
- src/PostHog/Features/LocalFeatureFlagsLoader.cs
- src/PostHog/Generated/VersionConstants.cs
- src/PostHog/PostHogClient.cs
- tests/UnitTests/Features/FeatureFlagsTests.cs
see this discussion here: https://github.com/PostHog/posthog-js/pull/1758#discussion_r1970563444
> chore(flags): update quota-limited logs

- Directory.Build.props
- samples/HogTied.Web/Filters/PostHogPageViewFilter.cs
- src/PostHog.AspNetCore/Cache/HttpContextFeatureFlagCache.cs
- src/PostHog/Capture/CaptureExtensions.cs
- src/PostHog/Generated/VersionConstants.cs
- tests/UnitTests.AspNetCore/HttpContextFeatureFlagCacheTests.cs
HttpContext.Items can be disposed by the time we're trying to set the cache. This is because we might be making in a background thread. In that case, we don't want to fail the operation.
Also added some overloads to `CapturePageView` and `CaptureScreen` that send feature flag data.
> Fix unhandled object disposed exception

- Directory.Build.props
- samples/HogTied.Web/Pages/Index.cshtml
- src/PostHog.AspNetCore/FeatureManagement/FeatureManagementExtensions.cs
- src/PostHog/Generated/VersionConstants.cs
- src/PostHog/IPostHogClient.cs
- src/PostHog/PostHogClient.cs
This method was there to support .NET Feature Management. For now, I'll just cast to `PostHogClient` and use reflection if the `IPostHogClient` isn't a `PostHogClient`. It's ugly, but it'll do for now.
I do see the benefit of a method to enumerate flag definitions on `IPostHogClient`, I just need to think it over a bit. Any method we add, we have to support. Do we do an `IAsyncEnumerabel` or a `Task<IReadOnlyList>` or something else?
Fixes #60
> Remove internal method from IPostHogClient interface

- samples/HogTied.Web/Pages/Index.cshtml
- samples/HogTied.Web/Pages/Index.cshtml.cs
Update the sample to show whether local eval is being used or not.
> Show whether we're using local eval or not

- src/PostHog.AspNetCore/Cache/HttpContextFeatureFlagCache.cs
- src/PostHog/Api/DecideApiResult.cs
- src/PostHog/Features/IFeatureFlagCache.cs
- src/PostHog/PostHogClient.cs
- tests/UnitTests.AspNetCore/HttpContextFeatureFlagCacheTests.cs
- tests/UnitTests/Features/FeatureFlagsTests.cs
- tests/UnitTests/Json/JsonSerializerHelperTests.cs
> Add requestId to the `$feature_flag_called` event.

- src/PostHog/Api/PostHogApiClient.cs
- src/PostHog/Features/FeatureFlagOptions.cs
- src/PostHog/PostHogClient.cs
- tests/TestLibrary/Fakes/FakeHttpMessageHandler.cs
- tests/TestLibrary/Fakes/FakeHttpMessageHandlerExtensions.cs
- tests/UnitTests/Features/FeatureFlagsTests.cs
This adds support for https://github.com/PostHog/posthog/pull/29493 which allows specifying a set of flag keys to evaluate.
Fixes #62
> feat(flags): Allow specifying flags to evaluate

- Directory.Build.props
- src/PostHog/Generated/VersionConstants.cs
- src/PostHog/Library/AsyncBatchHandler.cs
And just debug assert that they're not "coding error" exceptions.
We don't want to miss out on exception logging in our async batching that could cause the process to crash without good info.
And bump version to 1.0.4.
> Catch and log all exceptions

- Directory.Build.props
- samples/HogTied.Web/Pages/Index.cshtml.cs
- src/PostHog/Capture/CapturedEventBatchContext.cs
- src/PostHog/Config/PostHogOptions.cs
- src/PostHog/Features/FallbackFeatureFlagCache.cs
- src/PostHog/Features/FeatureFlagCacheBase.cs
- src/PostHog/Features/IFeatureFlagCache.cs
- src/PostHog/Features/MemoryFeatureFlagCache.cs
- src/PostHog/Generated/VersionConstants.cs
- src/PostHog/Library/AsyncBatchHandler.cs
- src/PostHog/PostHogClient.cs
- tests/UnitTests/Features/FallbackFeatureFlagCacheTests.cs
- tests/UnitTests/Features/MemoryFeatureFlagCacheTests.cs
- tests/UnitTests/Library/AsyncBatchHandlerTests.cs
- tests/UnitTests/PostHogClientTests.cs
When `sendFeatureFlags` is `true`, the client makes a `Decide` requests to get the latest feature flags in order to enrich the captured event with the current feature flag values.
However, when processing a batch, it doesn't make sense to make a decide request multiple times for the same `distinctId`. This PR adds an in-memory cache that lasts for the duration of the batch.
So far, I don't think a lot of the other client libraries actually use the `/batch` endpoint to batch requests. And if they do, I don't think they're caching `/decide` requests. This is a change I'd like to consider doing for all of the clients.
> Make less decide requests when enriching events

- tests/UnitTests/Fixtures/decide-api-result-v4.json
- tests/UnitTests/Json/JsonSerializerHelperTests.cs
Just making sure this library will be fine when we fix https://github.com/PostHog/posthog/issues/30569
> Add unit test for null condition index

- src/PostHog.AspNetCore/README.md
- src/PostHog/Api/PostHogApiClient.cs
- src/PostHog/Library/HttpClientExtensions.cs
- tests/TestLibrary/Fakes/FakeHttpMessageHandlerExtensions.cs
- tests/UnitTests/Features/FeatureFlagsTests.cs
It's not used nor needed.
Also added some docs on local evaluation.
> Remove token from local_evaluation API call

- .github/workflows/call-flags-project-board.yml
This reverts commit 70920f3bb681ee3e8f80587d8e429a48eda4a53a.
> Revert "Remove unnecessary workflow"

- src/PostHog/Api/LocalEvaluationApiResult.cs
We're introducing a new type of filter, "flag". When we do, we don't want local evaluation to fail because it can't serialize it.
> fix: Ensure serialization doesn't fail when encountering flag dependencies

- samples/HogTied.Web/Pages/Index.cshtml
- samples/HogTied.Web/appsettings.Development.json
- src/PostHog/Api/ComparisonOperator.cs
- src/PostHog/Api/PostHogApiClient.cs
- tests/TestLibrary/Fakes/FakeHttpMessageHandlerExtensions.cs
- tests/UnitTests/Features/FeatureFlagsTests.cs
- tests/UnitTests/Features/RemoteConfigTests.cs
- tests/UnitTests/PostHogClientTests.cs
Fixes the `remote_config` endpoint to include the project API key as a token parameter for deterministic project routing, matching the implementation in other server-side SDKs.
- Add token parameter to remote_config URL construction
- Add test to verify the token parameter is included in requests
- Update test fixtures to match new URL format
Also added `FlagEvaluatesTo` comparison operator so library doesn't break when encountering a flag dependency.
> fix: Pass project API key in `remote_config` and `local_evaluation` requests

- README.md
- tests/UnitTests/Features/FeatureFlagsTests.cs
- tests/UnitTests/UnitTests.csproj
Add `xunit.runner.visualstudio 2.4.5` for `netcoreapp3.1` target framework.
- Version `2.8.2` doesn't support `netcoreapp3.1`, causing "No test is available" warnings.
- Version `2.4.5` is the last version with `netcoreapp3.1` support.
This eliminates the warning while maintaining full test discovery and execution for both `netcoreapp3.1` (testing `netstandard2.1` compatibility) and `net8.0`.
> fix: test discovery warning for netcoreapp3.1
